settings:
  kubeContext: kind-maghaze
  maxHistory: 10
  timeout: 9000

namespaces:
  cert-manager:
    labels:
      managed-by: helmsman
  networking:
    labels:
      managed-by: helmsman
  monitoring:
    labels:
      managed-by: "helmsman"

helmRepos:
  jetstack: https://charts.jetstack.io
  datawire: "https://app.getambassador.io"
  ingress-nginx: https://kubernetes.github.io/ingress-nginx # https://spacelift.io/blog/kubernetes-ingress
  prometheus-community: "https://prometheus-community.github.io/helm-charts" # https://blog.container-solutions.com/prometheus-operator-beginners-guide

apps:
  # traffic-manager:
  #   name: traffic-manager
  #   namespace: networking
  #   priority: -9000
  #   chart: datawire/telepresence
  #   enabled: false
  #   version: 2.17.0
  #   wait: true
  #   timeout: 500

  cert-manager:
    name: cert-manager
    namespace: cert-manager
    priority: -250000
    chart: jetstack/cert-manager
    version: v1.13.2
    wait: true
    enabled: true
    hooks:
      preInstall: https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-45.1.1/charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
      postInstall: ../namespaces/cert-manager/cluster-issuer.yaml
    valuesFiles:
      - ../namespaces/cert-manager/values.yaml

  # ingress-nginx:
  #   name: ingress-nginx
  #   namespace: networking
  #   priority: -250000
  #   chart: ingress-nginx/ingress-nginx
  #   version: 4.7.1
  #   wait: true
  #   enabled: true
  #   hooks:
  #     preInstall: https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-45.1.1/charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
  #   valuesFiles:
  #     - ../networking/ingress-nginx/values.yaml

  # kube-prometheus-stack:
  #   name: kube-prometheus-stack
  #   namespace: monitoring
  #   priority: -200000
  #   chart: prometheus-community/kube-prometheus-stack
  #   version: 49.2.0
  #   wait: true
  #   timeout: 500
  #   enabled: true
  #   secretsFiles:
  #     - ../namespaces/monitoring/kube-prometheus-stack/staging.secrets.yaml
  #   valuesFiles:
  #     - ../namespaces/monitoring/kube-prometheus-stack/staging.values.yaml

  # goldpinger:
  #   name: goldpinger
  #   namespace: monitoring
  #   priority: -150000
  #   chart: ../../charts/goldpinger
  #   version: 5.5.0
  #   enabled: true
  #   valuesFiles:
  #     - ../namespaces/monitoring/goldpinger/values.yaml
